"""Examen

Revision ID: 268f7a8ced9c
Revises: 
Create Date: 2025-07-07 22:40:56.856806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268f7a8ced9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=100), nullable=False))
        batch_op.alter_column('archivo',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('examen_profesional_id_fkey'), type_='foreignkey')
        batch_op.drop_column('profesional_id')
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('examen', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('profesional_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('examen_profesional_id_fkey'), 'user', ['profesional_id'], ['id'])
        batch_op.alter_column('archivo',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###
